# Generated by Django 3.1.7 on 2021-04-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepfake',
            old_name='path',
            new_name='paths',
        ),
    ]
